version: '3.8'

services:
  db:
    container_name: odoo-db
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    build: .
    container_name: odoo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./odoo-core:/opt/odoo/odoo
      - ./addons:/opt/odoo/addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./filestore-data:/var/lib/odoo 
    networks:
      - backend

volumes:
  postgres_data:
  filestore-data:

networks:
  backend:
    driver: bridge
